### ISSUE TITLE
Fix script broken

### ISSUE THREAD

**Issue by davelab6** [googlefonts/gf-glyphs-scripts#30]
Traceback:

```
Start
Traceback (most recent call last):
  File "fixfonts.py", line 264, in <module>
    main()
  File "fixfonts.py", line 250, in main
    ttfs_gf = download_gf_family(font.familyName)
  File "/Users/dcrossland/src/github.com/googlefonts/gf-glyphs-scripts/Google Fonts/utils.py", line 66, in download_gf_family
    return fonts_from_zip(family_zip)
  File "/Users/dcrossland/src/github.com/googlefonts/gf-glyphs-scripts/Google Fonts/utils.py", line 58, in fonts_from_zip
    ttfs.append(TTFont(zipfile.open(file_name)))
  File "/Library/Python/2.7/site-packages/fonttools-3.25.0-py2.7.egg/fontTools/ttLib/ttFont.py", line 126, in __init__
    file.seek(0)
io.UnsupportedOperation: seek
End
```

**Comment by m4rc1e** [comment]
Can be closed. Fixed in #32
